/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AusgangRouteImport } from './routes/ausgang'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DirigentRouteImport } from './routes/dirigent'
import { Route as DirigentDokumenteRouteImport } from './routes/dirigent-dokumente'
import { Route as DirigentEinstellungenRouteImport } from './routes/dirigent-einstellungen'
import { Route as DokumenteRouteImport } from './routes/dokumente'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as ElternRouteImport } from './routes/eltern'
import { Route as ElternEinstellungenRouteImport } from './routes/eltern-einstellungen'
import { Route as KonzerteRouteImport } from './routes/konzerte'
import { Route as MusikerRouteImport } from './routes/musiker'
import { Route as ProbenRouteImport } from './routes/proben'
import { Route as ProgrammRouteImport } from './routes/programm'
import { Route as PutzplanRouteImport } from './routes/putzplan'
import { Route as TagebuchRouteImport } from './routes/tagebuch'
import { Route as TippsRouteImport } from './routes/tipps'
import { Route as VorbereitungRouteImport } from './routes/vorbereitung'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/admin.admin'
import { Route as AuthenticatedAdminAnwesenheitRouteImport } from './routes/_authenticated/admin.anwesenheit'
import { Route as AuthenticatedAdminBerichteRouteImport } from './routes/_authenticated/admin.berichte'
import { Route as AuthenticatedAdminDokumenteRouteImport } from './routes/_authenticated/admin.dokumente'
import { Route as AuthenticatedAdminEinstellungenRouteImport } from './routes/_authenticated/admin.einstellungen'
import { Route as AuthenticatedAdminElternRouteImport } from './routes/_authenticated/admin.eltern'
import { Route as AuthenticatedAdminInfosRouteImport } from './routes/_authenticated/admin.infos'
import { Route as AuthenticatedAdminKonzerteRouteImport } from './routes/_authenticated/admin.konzerte'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminPlanRouteImport } from './routes/_authenticated/admin.plan'
import { Route as AuthenticatedAdminProbenRouteImport } from './routes/_authenticated/admin.proben'
import { Route as AuthenticatedAdminRueckblickRouteImport } from './routes/_authenticated/admin.rueckblick'
import { Route as AuthenticatedAdminTageRouteImport } from './routes/_authenticated/admin.tage'
import { Route as AuthenticatedAdminTeilnehmerRouteImport } from './routes/_authenticated/admin.teilnehmer'
import { Route as AuthenticatedAdminVorbereitungRouteImport } from './routes/_authenticated/admin.vorbereitung'
import { Route as AuthenticatedAdminZimmerRouteImport } from './routes/_authenticated/admin.zimmer'
import { Route as ApiPublicPushCronRouteImport } from './routes/api/public/push-cron'
import { Route as AuthenticatedAdminTagDayIdRouteImport } from './routes/_authenticated/admin.tag.$dayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AusgangRoute = AusgangRouteImport.update({
  id: '/ausgang',
  path: '/ausgang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DirigentRoute = DirigentRouteImport.update({
  id: '/dirigent',
  path: '/dirigent',
  getParentRoute: () => rootRouteImport,
} as any)
const DirigentDokumenteRoute = DirigentDokumenteRouteImport.update({
  id: '/dirigent-dokumente',
  path: '/dirigent-dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const DirigentEinstellungenRoute = DirigentEinstellungenRouteImport.update({
  id: '/dirigent-einstellungen',
  path: '/dirigent-einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenteRoute = DokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ElternRoute = ElternRouteImport.update({
  id: '/eltern',
  path: '/eltern',
  getParentRoute: () => rootRouteImport,
} as any)
const ElternEinstellungenRoute = ElternEinstellungenRouteImport.update({
  id: '/eltern-einstellungen',
  path: '/eltern-einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KonzerteRoute = KonzerteRouteImport.update({
  id: '/konzerte',
  path: '/konzerte',
  getParentRoute: () => rootRouteImport,
} as any)
const MusikerRoute = MusikerRouteImport.update({
  id: '/musiker',
  path: '/musiker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbenRoute = ProbenRouteImport.update({
  id: '/proben',
  path: '/proben',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammRoute = ProgrammRouteImport.update({
  id: '/programm',
  path: '/programm',
  getParentRoute: () => rootRouteImport,
} as any)
const PutzplanRoute = PutzplanRouteImport.update({
  id: '/putzplan',
  path: '/putzplan',
  getParentRoute: () => rootRouteImport,
} as any)
const TagebuchRoute = TagebuchRouteImport.update({
  id: '/tagebuch',
  path: '/tagebuch',
  getParentRoute: () => rootRouteImport,
} as any)
const TippsRoute = TippsRouteImport.update({
  id: '/tipps',
  path: '/tipps',
  getParentRoute: () => rootRouteImport,
} as any)
const VorbereitungRoute = VorbereitungRouteImport.update({
  id: '/vorbereitung',
  path: '/vorbereitung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnwesenheitRoute =
  AuthenticatedAdminAnwesenheitRouteImport.update({
    id: '/anwesenheit',
    path: '/anwesenheit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBerichteRoute =
  AuthenticatedAdminBerichteRouteImport.update({
    id: '/berichte',
    path: '/berichte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDokumenteRoute =
  AuthenticatedAdminDokumenteRouteImport.update({
    id: '/dokumente',
    path: '/dokumente',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEinstellungenRoute =
  AuthenticatedAdminEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminElternRoute =
  AuthenticatedAdminElternRouteImport.update({
    id: '/eltern',
    path: '/eltern',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInfosRoute = AuthenticatedAdminInfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKonzerteRoute =
  AuthenticatedAdminKonzerteRouteImport.update({
    id: '/konzerte',
    path: '/konzerte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPlanRoute = AuthenticatedAdminPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProbenRoute =
  AuthenticatedAdminProbenRouteImport.update({
    id: '/proben',
    path: '/proben',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRueckblickRoute =
  AuthenticatedAdminRueckblickRouteImport.update({
    id: '/rueckblick',
    path: '/rueckblick',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTageRoute = AuthenticatedAdminTageRouteImport.update({
  id: '/tage',
  path: '/tage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeilnehmerRoute =
  AuthenticatedAdminTeilnehmerRouteImport.update({
    id: '/teilnehmer',
    path: '/teilnehmer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVorbereitungRoute =
  AuthenticatedAdminVorbereitungRouteImport.update({
    id: '/vorbereitung',
    path: '/vorbereitung',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminZimmerRoute =
  AuthenticatedAdminZimmerRouteImport.update({
    id: '/zimmer',
    path: '/zimmer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPushCronRoute = ApiPublicPushCronRouteImport.update({
  id: '/api/public/push-cron',
  path: '/api/public/push-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTagDayIdRoute =
  AuthenticatedAdminTagDayIdRouteImport.update({
    id: '/tag/$dayId',
    path: '/tag/$dayId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ausgang': typeof AusgangRoute
  '/auth': typeof AuthRoute
  '/dirigent': typeof DirigentRoute
  '/dirigent-dokumente': typeof DirigentDokumenteRoute
  '/dirigent-einstellungen': typeof DirigentEinstellungenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/eltern': typeof ElternRoute
  '/eltern-einstellungen': typeof ElternEinstellungenRoute
  '/konzerte': typeof KonzerteRoute
  '/musiker': typeof MusikerRoute
  '/proben': typeof ProbenRoute
  '/programm': typeof ProgrammRoute
  '/putzplan': typeof PutzplanRoute
  '/tagebuch': typeof TagebuchRoute
  '/tipps': typeof TippsRoute
  '/vorbereitung': typeof VorbereitungRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/admin': typeof AuthenticatedAdminAdminRoute
  '/admin/anwesenheit': typeof AuthenticatedAdminAnwesenheitRoute
  '/admin/berichte': typeof AuthenticatedAdminBerichteRoute
  '/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/eltern': typeof AuthenticatedAdminElternRoute
  '/admin/infos': typeof AuthenticatedAdminInfosRoute
  '/admin/konzerte': typeof AuthenticatedAdminKonzerteRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/plan': typeof AuthenticatedAdminPlanRoute
  '/admin/proben': typeof AuthenticatedAdminProbenRoute
  '/admin/rueckblick': typeof AuthenticatedAdminRueckblickRoute
  '/admin/tage': typeof AuthenticatedAdminTageRoute
  '/admin/teilnehmer': typeof AuthenticatedAdminTeilnehmerRoute
  '/admin/vorbereitung': typeof AuthenticatedAdminVorbereitungRoute
  '/admin/zimmer': typeof AuthenticatedAdminZimmerRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/tag/$dayId': typeof AuthenticatedAdminTagDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ausgang': typeof AusgangRoute
  '/auth': typeof AuthRoute
  '/dirigent': typeof DirigentRoute
  '/dirigent-dokumente': typeof DirigentDokumenteRoute
  '/dirigent-einstellungen': typeof DirigentEinstellungenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/eltern': typeof ElternRoute
  '/eltern-einstellungen': typeof ElternEinstellungenRoute
  '/konzerte': typeof KonzerteRoute
  '/musiker': typeof MusikerRoute
  '/proben': typeof ProbenRoute
  '/programm': typeof ProgrammRoute
  '/putzplan': typeof PutzplanRoute
  '/tagebuch': typeof TagebuchRoute
  '/tipps': typeof TippsRoute
  '/vorbereitung': typeof VorbereitungRoute
  '/admin/admin': typeof AuthenticatedAdminAdminRoute
  '/admin/anwesenheit': typeof AuthenticatedAdminAnwesenheitRoute
  '/admin/berichte': typeof AuthenticatedAdminBerichteRoute
  '/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/eltern': typeof AuthenticatedAdminElternRoute
  '/admin/infos': typeof AuthenticatedAdminInfosRoute
  '/admin/konzerte': typeof AuthenticatedAdminKonzerteRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/plan': typeof AuthenticatedAdminPlanRoute
  '/admin/proben': typeof AuthenticatedAdminProbenRoute
  '/admin/rueckblick': typeof AuthenticatedAdminRueckblickRoute
  '/admin/tage': typeof AuthenticatedAdminTageRoute
  '/admin/teilnehmer': typeof AuthenticatedAdminTeilnehmerRoute
  '/admin/vorbereitung': typeof AuthenticatedAdminVorbereitungRoute
  '/admin/zimmer': typeof AuthenticatedAdminZimmerRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/tag/$dayId': typeof AuthenticatedAdminTagDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ausgang': typeof AusgangRoute
  '/auth': typeof AuthRoute
  '/dirigent': typeof DirigentRoute
  '/dirigent-dokumente': typeof DirigentDokumenteRoute
  '/dirigent-einstellungen': typeof DirigentEinstellungenRoute
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRoute
  '/eltern': typeof ElternRoute
  '/eltern-einstellungen': typeof ElternEinstellungenRoute
  '/konzerte': typeof KonzerteRoute
  '/musiker': typeof MusikerRoute
  '/proben': typeof ProbenRoute
  '/programm': typeof ProgrammRoute
  '/putzplan': typeof PutzplanRoute
  '/tagebuch': typeof TagebuchRoute
  '/tipps': typeof TippsRoute
  '/vorbereitung': typeof VorbereitungRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/admin/anwesenheit': typeof AuthenticatedAdminAnwesenheitRoute
  '/_authenticated/admin/berichte': typeof AuthenticatedAdminBerichteRoute
  '/_authenticated/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/_authenticated/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/_authenticated/admin/eltern': typeof AuthenticatedAdminElternRoute
  '/_authenticated/admin/infos': typeof AuthenticatedAdminInfosRoute
  '/_authenticated/admin/konzerte': typeof AuthenticatedAdminKonzerteRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/plan': typeof AuthenticatedAdminPlanRoute
  '/_authenticated/admin/proben': typeof AuthenticatedAdminProbenRoute
  '/_authenticated/admin/rueckblick': typeof AuthenticatedAdminRueckblickRoute
  '/_authenticated/admin/tage': typeof AuthenticatedAdminTageRoute
  '/_authenticated/admin/teilnehmer': typeof AuthenticatedAdminTeilnehmerRoute
  '/_authenticated/admin/vorbereitung': typeof AuthenticatedAdminVorbereitungRoute
  '/_authenticated/admin/zimmer': typeof AuthenticatedAdminZimmerRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/tag/$dayId': typeof AuthenticatedAdminTagDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ausgang'
    | '/auth'
    | '/dirigent'
    | '/dirigent-dokumente'
    | '/dirigent-einstellungen'
    | '/dokumente'
    | '/einstellungen'
    | '/eltern'
    | '/eltern-einstellungen'
    | '/konzerte'
    | '/musiker'
    | '/proben'
    | '/programm'
    | '/putzplan'
    | '/tagebuch'
    | '/tipps'
    | '/vorbereitung'
    | '/admin'
    | '/admin/admin'
    | '/admin/anwesenheit'
    | '/admin/berichte'
    | '/admin/dokumente'
    | '/admin/einstellungen'
    | '/admin/eltern'
    | '/admin/infos'
    | '/admin/konzerte'
    | '/admin/news'
    | '/admin/plan'
    | '/admin/proben'
    | '/admin/rueckblick'
    | '/admin/tage'
    | '/admin/teilnehmer'
    | '/admin/vorbereitung'
    | '/admin/zimmer'
    | '/api/public/push-cron'
    | '/admin/'
    | '/admin/tag/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ausgang'
    | '/auth'
    | '/dirigent'
    | '/dirigent-dokumente'
    | '/dirigent-einstellungen'
    | '/dokumente'
    | '/einstellungen'
    | '/eltern'
    | '/eltern-einstellungen'
    | '/konzerte'
    | '/musiker'
    | '/proben'
    | '/programm'
    | '/putzplan'
    | '/tagebuch'
    | '/tipps'
    | '/vorbereitung'
    | '/admin/admin'
    | '/admin/anwesenheit'
    | '/admin/berichte'
    | '/admin/dokumente'
    | '/admin/einstellungen'
    | '/admin/eltern'
    | '/admin/infos'
    | '/admin/konzerte'
    | '/admin/news'
    | '/admin/plan'
    | '/admin/proben'
    | '/admin/rueckblick'
    | '/admin/tage'
    | '/admin/teilnehmer'
    | '/admin/vorbereitung'
    | '/admin/zimmer'
    | '/api/public/push-cron'
    | '/admin'
    | '/admin/tag/$dayId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ausgang'
    | '/auth'
    | '/dirigent'
    | '/dirigent-dokumente'
    | '/dirigent-einstellungen'
    | '/dokumente'
    | '/einstellungen'
    | '/eltern'
    | '/eltern-einstellungen'
    | '/konzerte'
    | '/musiker'
    | '/proben'
    | '/programm'
    | '/putzplan'
    | '/tagebuch'
    | '/tipps'
    | '/vorbereitung'
    | '/_authenticated/admin'
    | '/_authenticated/admin/admin'
    | '/_authenticated/admin/anwesenheit'
    | '/_authenticated/admin/berichte'
    | '/_authenticated/admin/dokumente'
    | '/_authenticated/admin/einstellungen'
    | '/_authenticated/admin/eltern'
    | '/_authenticated/admin/infos'
    | '/_authenticated/admin/konzerte'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/plan'
    | '/_authenticated/admin/proben'
    | '/_authenticated/admin/rueckblick'
    | '/_authenticated/admin/tage'
    | '/_authenticated/admin/teilnehmer'
    | '/_authenticated/admin/vorbereitung'
    | '/_authenticated/admin/zimmer'
    | '/api/public/push-cron'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/tag/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AusgangRoute: typeof AusgangRoute
  AuthRoute: typeof AuthRoute
  DirigentRoute: typeof DirigentRoute
  DirigentDokumenteRoute: typeof DirigentDokumenteRoute
  DirigentEinstellungenRoute: typeof DirigentEinstellungenRoute
  DokumenteRoute: typeof DokumenteRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ElternRoute: typeof ElternRoute
  ElternEinstellungenRoute: typeof ElternEinstellungenRoute
  KonzerteRoute: typeof KonzerteRoute
  MusikerRoute: typeof MusikerRoute
  ProbenRoute: typeof ProbenRoute
  ProgrammRoute: typeof ProgrammRoute
  PutzplanRoute: typeof PutzplanRoute
  TagebuchRoute: typeof TagebuchRoute
  TippsRoute: typeof TippsRoute
  VorbereitungRoute: typeof VorbereitungRoute
  ApiPublicPushCronRoute: typeof ApiPublicPushCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ausgang': {
      id: '/ausgang'
      path: '/ausgang'
      fullPath: '/ausgang'
      preLoaderRoute: typeof AusgangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirigent': {
      id: '/dirigent'
      path: '/dirigent'
      fullPath: '/dirigent'
      preLoaderRoute: typeof DirigentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirigent-dokumente': {
      id: '/dirigent-dokumente'
      path: '/dirigent-dokumente'
      fullPath: '/dirigent-dokumente'
      preLoaderRoute: typeof DirigentDokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirigent-einstellungen': {
      id: '/dirigent-einstellungen'
      path: '/dirigent-einstellungen'
      fullPath: '/dirigent-einstellungen'
      preLoaderRoute: typeof DirigentEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumente': {
      id: '/dokumente'
      path: '/dokumente'
      fullPath: '/dokumente'
      preLoaderRoute: typeof DokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eltern': {
      id: '/eltern'
      path: '/eltern'
      fullPath: '/eltern'
      preLoaderRoute: typeof ElternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eltern-einstellungen': {
      id: '/eltern-einstellungen'
      path: '/eltern-einstellungen'
      fullPath: '/eltern-einstellungen'
      preLoaderRoute: typeof ElternEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konzerte': {
      id: '/konzerte'
      path: '/konzerte'
      fullPath: '/konzerte'
      preLoaderRoute: typeof KonzerteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musiker': {
      id: '/musiker'
      path: '/musiker'
      fullPath: '/musiker'
      preLoaderRoute: typeof MusikerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proben': {
      id: '/proben'
      path: '/proben'
      fullPath: '/proben'
      preLoaderRoute: typeof ProbenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm': {
      id: '/programm'
      path: '/programm'
      fullPath: '/programm'
      preLoaderRoute: typeof ProgrammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putzplan': {
      id: '/putzplan'
      path: '/putzplan'
      fullPath: '/putzplan'
      preLoaderRoute: typeof PutzplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagebuch': {
      id: '/tagebuch'
      path: '/tagebuch'
      fullPath: '/tagebuch'
      preLoaderRoute: typeof TagebuchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipps': {
      id: '/tipps'
      path: '/tipps'
      fullPath: '/tipps'
      preLoaderRoute: typeof TippsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorbereitung': {
      id: '/vorbereitung'
      path: '/vorbereitung'
      fullPath: '/vorbereitung'
      preLoaderRoute: typeof VorbereitungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admin': {
      id: '/_authenticated/admin/admin'
      path: '/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anwesenheit': {
      id: '/_authenticated/admin/anwesenheit'
      path: '/anwesenheit'
      fullPath: '/admin/anwesenheit'
      preLoaderRoute: typeof AuthenticatedAdminAnwesenheitRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/berichte': {
      id: '/_authenticated/admin/berichte'
      path: '/berichte'
      fullPath: '/admin/berichte'
      preLoaderRoute: typeof AuthenticatedAdminBerichteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dokumente': {
      id: '/_authenticated/admin/dokumente'
      path: '/dokumente'
      fullPath: '/admin/dokumente'
      preLoaderRoute: typeof AuthenticatedAdminDokumenteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/einstellungen': {
      id: '/_authenticated/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eltern': {
      id: '/_authenticated/admin/eltern'
      path: '/eltern'
      fullPath: '/admin/eltern'
      preLoaderRoute: typeof AuthenticatedAdminElternRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/infos': {
      id: '/_authenticated/admin/infos'
      path: '/infos'
      fullPath: '/admin/infos'
      preLoaderRoute: typeof AuthenticatedAdminInfosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/konzerte': {
      id: '/_authenticated/admin/konzerte'
      path: '/konzerte'
      fullPath: '/admin/konzerte'
      preLoaderRoute: typeof AuthenticatedAdminKonzerteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plan': {
      id: '/_authenticated/admin/plan'
      path: '/plan'
      fullPath: '/admin/plan'
      preLoaderRoute: typeof AuthenticatedAdminPlanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proben': {
      id: '/_authenticated/admin/proben'
      path: '/proben'
      fullPath: '/admin/proben'
      preLoaderRoute: typeof AuthenticatedAdminProbenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rueckblick': {
      id: '/_authenticated/admin/rueckblick'
      path: '/rueckblick'
      fullPath: '/admin/rueckblick'
      preLoaderRoute: typeof AuthenticatedAdminRueckblickRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tage': {
      id: '/_authenticated/admin/tage'
      path: '/tage'
      fullPath: '/admin/tage'
      preLoaderRoute: typeof AuthenticatedAdminTageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teilnehmer': {
      id: '/_authenticated/admin/teilnehmer'
      path: '/teilnehmer'
      fullPath: '/admin/teilnehmer'
      preLoaderRoute: typeof AuthenticatedAdminTeilnehmerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vorbereitung': {
      id: '/_authenticated/admin/vorbereitung'
      path: '/vorbereitung'
      fullPath: '/admin/vorbereitung'
      preLoaderRoute: typeof AuthenticatedAdminVorbereitungRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/zimmer': {
      id: '/_authenticated/admin/zimmer'
      path: '/zimmer'
      fullPath: '/admin/zimmer'
      preLoaderRoute: typeof AuthenticatedAdminZimmerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/push-cron': {
      id: '/api/public/push-cron'
      path: '/api/public/push-cron'
      fullPath: '/api/public/push-cron'
      preLoaderRoute: typeof ApiPublicPushCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tag/$dayId': {
      id: '/_authenticated/admin/tag/$dayId'
      path: '/tag/$dayId'
      fullPath: '/admin/tag/$dayId'
      preLoaderRoute: typeof AuthenticatedAdminTagDayIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminAnwesenheitRoute: typeof AuthenticatedAdminAnwesenheitRoute
  AuthenticatedAdminBerichteRoute: typeof AuthenticatedAdminBerichteRoute
  AuthenticatedAdminDokumenteRoute: typeof AuthenticatedAdminDokumenteRoute
  AuthenticatedAdminEinstellungenRoute: typeof AuthenticatedAdminEinstellungenRoute
  AuthenticatedAdminElternRoute: typeof AuthenticatedAdminElternRoute
  AuthenticatedAdminInfosRoute: typeof AuthenticatedAdminInfosRoute
  AuthenticatedAdminKonzerteRoute: typeof AuthenticatedAdminKonzerteRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPlanRoute: typeof AuthenticatedAdminPlanRoute
  AuthenticatedAdminProbenRoute: typeof AuthenticatedAdminProbenRoute
  AuthenticatedAdminRueckblickRoute: typeof AuthenticatedAdminRueckblickRoute
  AuthenticatedAdminTageRoute: typeof AuthenticatedAdminTageRoute
  AuthenticatedAdminTeilnehmerRoute: typeof AuthenticatedAdminTeilnehmerRoute
  AuthenticatedAdminVorbereitungRoute: typeof AuthenticatedAdminVorbereitungRoute
  AuthenticatedAdminZimmerRoute: typeof AuthenticatedAdminZimmerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTagDayIdRoute: typeof AuthenticatedAdminTagDayIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminAnwesenheitRoute: AuthenticatedAdminAnwesenheitRoute,
  AuthenticatedAdminBerichteRoute: AuthenticatedAdminBerichteRoute,
  AuthenticatedAdminDokumenteRoute: AuthenticatedAdminDokumenteRoute,
  AuthenticatedAdminEinstellungenRoute: AuthenticatedAdminEinstellungenRoute,
  AuthenticatedAdminElternRoute: AuthenticatedAdminElternRoute,
  AuthenticatedAdminInfosRoute: AuthenticatedAdminInfosRoute,
  AuthenticatedAdminKonzerteRoute: AuthenticatedAdminKonzerteRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminPlanRoute: AuthenticatedAdminPlanRoute,
  AuthenticatedAdminProbenRoute: AuthenticatedAdminProbenRoute,
  AuthenticatedAdminRueckblickRoute: AuthenticatedAdminRueckblickRoute,
  AuthenticatedAdminTageRoute: AuthenticatedAdminTageRoute,
  AuthenticatedAdminTeilnehmerRoute: AuthenticatedAdminTeilnehmerRoute,
  AuthenticatedAdminVorbereitungRoute: AuthenticatedAdminVorbereitungRoute,
  AuthenticatedAdminZimmerRoute: AuthenticatedAdminZimmerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTagDayIdRoute: AuthenticatedAdminTagDayIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AusgangRoute: AusgangRoute,
  AuthRoute: AuthRoute,
  DirigentRoute: DirigentRoute,
  DirigentDokumenteRoute: DirigentDokumenteRoute,
  DirigentEinstellungenRoute: DirigentEinstellungenRoute,
  DokumenteRoute: DokumenteRoute,
  EinstellungenRoute: EinstellungenRoute,
  ElternRoute: ElternRoute,
  ElternEinstellungenRoute: ElternEinstellungenRoute,
  KonzerteRoute: KonzerteRoute,
  MusikerRoute: MusikerRoute,
  ProbenRoute: ProbenRoute,
  ProgrammRoute: ProgrammRoute,
  PutzplanRoute: PutzplanRoute,
  TagebuchRoute: TagebuchRoute,
  TippsRoute: TippsRoute,
  VorbereitungRoute: VorbereitungRoute,
  ApiPublicPushCronRoute: ApiPublicPushCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
