-- Instrumente aus der Schuelerliste (ドイツ交流_来校生徒情報.xlsx) + Konzertprogramm 24./25.10.
WITH src(first, last, instr) AS (VALUES
  ('philine','wolf','Flöte'),
  ('evangelos','masis','Saxophon'),
  ('catharina','splitt','Klarinette'),
  ('lennart','huckstadt','Flöte'),
  ('kai','schoenrock','Trompete'),
  ('konstantina-yoana','stefanova','Flöte'),
  ('erik','bach','Klarinette'),
  ('timur','ucar','Horn'),
  ('sofie','lehmann','Klarinette'),
  ('richard','seidel','Saxophon'),
  ('oskar','dosse','Tenorsaxophon'),
  ('maxim','heinken','Saxophon'),
  ('ludwig','treppesch','Klarinette'),
  ('lina','schulze','Bass'),
  ('lasse','staschen','Trompete'),
  ('julie','geller','Altsaxophon'),
  ('ida','coujad','Posaune'),
  ('helena','kampe','Klarinette'),
  ('hadrian','ivanov','Trompete'),
  ('enno','wenz','Klarinette'),
  ('elisa','grosse','Klarinette'),
  ('tamina','thebus','Posaune'),
  ('minh','nguyen','Euphonium'),
  ('mika','vosgerau','Schlagwerk'),
  ('max','uhlhorn','Schlagwerk'),
  ('marlene','hauck','Klarinette'),
  ('jonas','hoesch','Klarinette'),
  ('jo','wanitschke','Altsaxophon'),
  ('finn','zeplin','Schlagwerk'),
  ('clara','borchard','Flöte'),
  ('cedric','weissmuller','Trompete'),
  ('anisia','kerdei','Flöte'),
  ('alisa','burmeister','Flöte'),
  ('tess','poulsen','Klarinette'),
  ('sam','piotraschke','Klarinette'),
  ('rike','wenz','Trompete'),
  ('luisa','specker','Flöte'),
  ('luis','hardt','Flöte'),
  ('lucas','wunder','Trompete'),
  ('jens','rondeck','Schlagwerk'),
  ('helena','kracke','Trompete'),
  ('elias','jacobs','Klarinette'),
  ('ares','taskin','Posaune'),
  ('anne','schemm','Altsaxophon'),
  ('amalia','masis','Flöte'),
  ('amadeus','haase','Tuba'),
  ('nelly','heinken','Klarinette'),
  ('max','bolder','Flöte'),
  ('luise','montanus','Klarinette'),
  ('karl','otto','Horn'),
  ('karl','fester','Flöte'),
  ('johannes','hauck','Saxophon'),
  ('friederike','specht','Posaune'),
  ('clara','schuller','Bassklarinette'),
  ('natsumi','aoki','Klarinette'),
  ('mats','steffel','Posaune'),
  ('leyla','al-khawlany','Klarinette'),
  ('jonas','keil','Saxophon'),
  ('jasper','benedix','Horn'),
  ('mio','uno','Trompete'),
  ('miyuu','aoki','Trompete'),
  ('maximilian','roolvink','Trompete'),
  ('matteo','mix','Posaune'),
  ('mats','lemke','Horn'),
  ('johann','klein','Klarinette')
)
UPDATE public.participants p
SET instrument = s.instr
FROM src s
WHERE translate(lower(split_part(p.first_name, ' ', 1)), 'üöäéíç', 'uoaeic') = s.first
  AND translate(lower(regexp_replace(p.last_name, '^.* ', '')), 'üöäéíç', 'uoaeic') = s.last;

INSERT INTO public.concerts (trip_id, title, venue, starts_at, program, notes, published, sort_order)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'Schulkonzert (kleine Besetzung)', 'Inage-Schule', '2026-10-23T15:00:00+09:00', '{}', 'Kleinere Besetzung – Programm folgt.', true, 1),
  ('11111111-1111-1111-1111-111111111111', 'Austauschkonzert Inage-Schule', 'Inage-Schule', '2026-10-24T15:00:00+09:00', ARRAY['Arsenal','Dreamcatcher','Extraordinary Machines of Clockwork and Steam','Florentiner','Deep Purple Medley','Sing Sing Sing','Mambo','We are the World'], '', true, 2),
  ('11111111-1111-1111-1111-111111111111', 'Austauschkonzert Hiroo High School', 'Hiroo High School, Tokio', '2026-10-25T15:00:00+09:00', ARRAY['Arsenal','Dreamcatcher','Extraordinary Machines of Clockwork and Steam','Florentiner','Deep Purple Medley','Sing Sing Sing','Mambo','We are the World'], '', true, 3);
